--
-- PostgreSQL database dump
--

\restrict M3tXNOdigkhhDk2QfadMfAfgWcEBjOGnCLeUfKOm8EYQFPoYduBiO1yfIg5rbeP

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-05-15 00:55:50

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 238 (class 1259 OID 16560)
-- Name: app_member; Type: TABLE; Schema: public; Owner: member
--

CREATE TABLE public.app_member (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.app_member OWNER TO member;

--
-- TOC entry 237 (class 1259 OID 16559)
-- Name: app_member_id_seq; Type: SEQUENCE; Schema: public; Owner: member
--

ALTER TABLE public.app_member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5044 (class 0 OID 16560)
-- Dependencies: 238
-- Data for Name: app_member; Type: TABLE DATA; Schema: public; Owner: member
--

COPY public.app_member (id, name, description) FROM stdin;
1	Juan Luna	Juan Luna is a BS IT student.
2	Roni Magiting	Roni is also a BS IT student
3	Debu Maliksi	Roni is a BS CS student
\.


--
-- TOC entry 5050 (class 0 OID 0)
-- Dependencies: 237
-- Name: app_member_id_seq; Type: SEQUENCE SET; Schema: public; Owner: member
--

SELECT pg_catalog.setval('public.app_member_id_seq', 2, true);


--
-- TOC entry 4895 (class 2606 OID 16569)
-- Name: app_member app_member_pkey; Type: CONSTRAINT; Schema: public; Owner: member
--

ALTER TABLE ONLY public.app_member
    ADD CONSTRAINT app_member_pkey PRIMARY KEY (id);


-- Completed on 2026-05-15 00:55:51

--
-- PostgreSQL database dump complete
--

\unrestrict M3tXNOdigkhhDk2QfadMfAfgWcEBjOGnCLeUfKOm8EYQFPoYduBiO1yfIg5rbeP

